# Generated by Django 4.1.4 on 2023-01-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='team3',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='team4',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='team5',
        ),
    ]
