# Generated by Django 4.1.4 on 2023-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_team_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='confirm_pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='确认密码/confirm_password'),
        ),
    ]
