# Generated by Django 4.1.4 on 2023-01-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_userinfo_confirm_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tnmt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnmtname', models.CharField(max_length=32, verbose_name='赛事/Tournament')),
                ('divi', models.CharField(choices=[('混合/Mixed', '混合/Mixed'), ('公开/Open', '公开/Open'), ('女子/Women', '女子/Women')], max_length=32, verbose_name='组别/Division')),
                ('host', models.CharField(max_length=32, verbose_name='主办姓名/Host name')),
                ('prov', models.CharField(blank=True, max_length=32, null=True, verbose_name='省/Province')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='市/City')),
                ('s_date', models.DateField(verbose_name='开始日期/Start date')),
                ('e_date', models.DateField(verbose_name='结束日期/End date')),
                ('intro', models.CharField(blank=True, max_length=512, null=True, verbose_name='简介/Intro')),
                ('appro', models.CharField(max_length=32, verbose_name='通过')),
            ],
        ),
    ]
