# Generated by Django 4.1.4 on 2023-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_team_teamname_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sch_type',
            field=models.CharField(choices=[('b2', '单场比赛'), ('b4', '4队淘汰赛'), ('b6', '6队淘汰赛'), ('b8', '8队淘汰赛'), ('b12', '12队淘汰赛'), ('b16', '16队淘汰赛'), ('2p3', '2组6队小组赛'), ('2p4', '2组8队小组赛'), ('2p5', '2组10队小组赛'), ('2p6', '2组12队小组赛'), ('3p3', '3组9队小组赛'), ('3p4', '3组12队小组赛'), ('4p3', '4组12队小组赛'), ('4p4', '4组16队小组赛'), ('4p5', '4组20队小组赛')], max_length=32),
        ),
    ]
