# Generated by Django 4.1.4 on 2023-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_game_sch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_info',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='时间&场地'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='比赛编号'),
        ),
    ]
