# Generated by Django 4.1.4 on 2023-01-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_game_game_info_alter_game_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='sch_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='sch_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
