# Generated by Django 4.1.4 on 2023-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_game_game_id_alter_game_sch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
