# Generated by Django 4.1.4 on 2023-02-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_game_away_alter_game_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='tnmt_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
