# Generated by Django 4.1.4 on 2023-02-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_game_date_game_tnmt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sch_type',
            field=models.CharField(choices=[('b2', '单场比赛'), ('b4', '4队淘汰赛'), ('b6', '6队淘汰赛'), ('b8', '8队淘汰赛'), ('b12', '12队淘汰赛'), ('b16', '16队淘汰赛'), ('1p3', '1组3队小组赛'), ('1p4', '1组4队小组赛'), ('1p5', '1组5队小组赛'), ('1p6', '1组6队小组赛'), ('2p3', '2组6队小组赛'), ('2p4', '2组8队小组赛'), ('2p5', '2组10队小组赛'), ('2p6', '2组12队小组赛'), ('3p3', '3组9队小组赛'), ('3p4', '3组12队小组赛'), ('4p3', '4组12队小组赛'), ('4p4', '4组16队小组赛'), ('4p5', '4组20队小组赛')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tnmt',
            name='e_date',
            field=models.DateField(verbose_name='结束日期/End date (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='tnmt',
            name='s_date',
            field=models.DateField(verbose_name='开始日期/Start date (YYYY-MM-DD)'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='DOB',
            field=models.DateTimeField(verbose_name='生日/DoB (YYYY-MM-DD)'),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_id', models.IntegerField()),
                ('pool_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=32, null=True)),
                ('result', models.CharField(blank=True, default='0-0', max_length=32, null=True)),
                ('score_d', models.CharField(blank=True, max_length=32, null=True)),
                ('tnmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.tnmt')),
            ],
        ),
    ]
