# Generated by Django 4.1.4 on 2023-02-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_game_sch_type_alter_tnmt_e_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnmt',
            name='intro',
        ),
        migrations.AddField(
            model_name='tnmt',
            name='o_link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='外链/Link'),
        ),
    ]
