# Generated by Django 4.1.4 on 2023-02-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_remove_tnmt_intro_tnmt_o_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='DOB',
            field=models.DateField(verbose_name='生日/DoB (YYYY-MM-DD)'),
        ),
    ]
